[package]
edition = "2021"
exclude = ["index.node"]
license = "GPL-3.0"
name = "desktop_native"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[features]
default = []
manual_test = []

[dependencies]
aes = "=0.8.4"
anyhow = "=1.0.86"
arboard = { version = "=3.3.2", default-features = false, features = ["wayland-data-control"] }
base64 = "=0.22.1"
cbc = { version = "=0.1.2", features = ["alloc"] }
futures = "0.3.30"
napi = { version = "=2.16.0", features = ["async", "tokio_rt"] }
napi-derive = "=2.16.0"
openssl = { version = "0.10.64", features = ["vendored"] }
openssl-src = "300.3.1"
rand = "=0.8.5"
retry = "=2.0.0"
scopeguard = "=1.2.0"
serde = "1.0.203"
serde_json = "1.0.117"
sha2 = "=0.10.8"
thiserror = "=1.0.58"
typenum = "=1.17.0"
webauthn-authenticator-rs = { version = "0.5.0", features = ["usb"] }
webauthn-rs = "0.5.0"

[build-dependencies]
napi-build = "=2.1.2"

[target.'cfg(windows)'.dependencies]
widestring = "=1.0.2"
windows = { version = "=0.54.0", features = [
  "Foundation",
  "Security_Credentials_UI",
  "Security_Cryptography",
  "Storage_Streams",
  "Win32_Foundation",
  "Win32_Security_Credentials",
  "Win32_System_WinRT",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging",
] }

[target.'cfg(windows)'.dev-dependencies]
keytar = "=0.1.6"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "=0.9.4"
security-framework = "=2.9.2"
security-framework-sys = "=2.9.1"

[target.'cfg(target_os = "linux")'.dependencies]
gio = "=0.19.2"
libsecret = "=0.5.0"
